name: Build Single File EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Requirements
        run: |
          pip install customtkinter pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --name "Alsayf-Single-Final" run.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Alsayf-Single-Final
          path: dist/Alsayf-Single-Final.exe
